#!/usr/bin/env bash

set -eu -o pipefail

if [[ ! -v CONTAINER_BASE ]]; then
    echo "missing CONTAINER_BASE" >&2
    exit 1
fi

VERSION="$(cat ./version.txt)"

function container-name {
    echo "${CONTAINER_BASE}-builder-$1:$VERSION"
}

docker build . -f ./Dockerfile.base -t base-container

for dockerfile in Dockerfile.*; do
    target="$(container-name "${dockerfile#Dockerfile.}")"
    echo "dockerfile: $dockerfile target: $target"

    docker build . -f "$dockerfile" -t "$target"
    if [[ ! -v DONT_PUSH ]]; then
        docker push "$target"
    fi
done
