# CMake Toolchain file for Linux ARM64 (aarch64) cross-compilation

SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR aarch64)

# Specify the cross compiler
SET(TOOLCHAIN_PREFIX aarch64-linux-gnu)
SET(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)

# Use ccache for faster rebuilds
find_program(CCACHE_PROGRAM ccache)
if(CCACHE_PROGRAM)
    SET(CMAKE_C_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
    SET(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
endif()

# Where is the target environment
SET(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}" /usr/${TOOLCHAIN_PREFIX})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# para pacotes cmake/pkg-config no staging
set(CMAKE_PREFIX_PATH "${CMAKE_SYSROOT}")
set(PKG_CONFIG_PATH "${CMAKE_SYSROOT}/lib/pkgconfig")

